name: Playwright Framework CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright/python:v1.49.1-noble
      options: --shm-size=1g

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up pipx and poetry
        run: |
          python3 -m pip install --user pipx
          export PATH="$HOME/.local/bin:$PATH"
          pipx install poetry

      - name: Install dependencies
        run: poetry install

      - name: Install Playwright Browsers
        run: poetry run playwright install

      - name: Run pytest tests
        env:
          HEADLESS: true
          BROWSERS: chromium
          DEVICES: ''
          LOG_LEVEL: DEBUG
        run: poetry run pytest tests

      - name: Run behave tests
        env:
          HEADLESS: true
          BROWSERS: chromium
          DEVICES: ''
          LOG_LEVEL: DEBUG
        run: poetry run behave features
